### ISSUE TITLE
Add examples for stardust 

### ISSUE THREAD

**Issue by laumair** [iotaledger/iota.lib.js#887]
## Description

Add examples to cover the following:

- [x] Minting collection NFT, minting NFTs under that collection iotaledger/iota.js#891
- [x] Transferring ownership of collection NFT to someone else iotaledger/iota.js#891
- [x] Transferring NFT within collection / or just pure NFT to someone else iotaledger/iota.js#891
- [x] Burning NFT / Burning Collection NFT iotaledger/iota.js#891
- [x] NFT Transfer with “Expiration Unlock Condition”. Target Address have certain time to claim the NFT.
- [x] Simple token transfer iotaledger/iota.js#888
- [x] Changing Token supply in the foundry iotaledger/iota.js#888
- [x] Locking token supply (applying vesting) via unlock conditions iotaledger/iota.js#888
